package com.service.databaseservice.repository;

import com.service.databaseservice.model.RepetitionModel;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.Optional;

public interface RepetitionRepository extends JpaRepository<RepetitionModel, Long> {
    @SuppressWarnings("java:S100") // autogenerated by hibernate
    Optional<RepetitionModel> getRepetitionByCard_Id(Long cardId);
}
